#!/bin/sh

readonly hunspell="hunspell -d en_US"

skip_spellcheck=0

display_usage() {
	echo "Usage: pcheck [-h|-s]"
	echo ""
	echo "    -h - show this help"
	echo "    -s - skip spellcheck"
	echo ""
	exit
}

reinplace_file() {
	local file="${1}" expr="${2}"
	
	[ -n "${expr}" ] || return
	sed -E "${expr}" ${file} > ${file}.new
	mv ${file}.new ${file}
}

while getopts "hs" option; do
	case ${option} in
	s)
		skip_spellcheck=1 ;;
	*)
		display_usage
	esac
done

if [ -z "$(make -V PKGNAME 2>/dev/null)" ]; then
	echo "===> This is not port directory"
	exit 1
fi

descr_file="$(make -V DESCR)"

rej_files="$(find -E . -name "*.rej" ! -regex '\./(\.svn|work)/.*')"
if [ -n "${rej_files}" ]; then
	echo "===> Found rejected patch file(s)"
	echo " ${rej_files}" | sed 's|./||g'
	exit 1
fi

find -E . \( -name "*.orig" -or -size 0 \) ! -regex '\./(\.svn|work)/.*' -delete
if [ ${skip_spellcheck} -eq 0 ]; then
	if [ -n "$(whereis -bq hunspell)" ]; then
		[ -f "${descr_file}" ] && ${hunspell} "${descr_file}"
		[ -f pkg-message ] && ${hunspell} pkg-message
		[ -f files/pkg-message.in ] && ${hunspell} files/pkg-message.in
	else
		echo "===> Hunspell not found, skipping spellcheck"
	fi
fi

find -E . -type f ! -regex '\./(\.svn|work)/.*' | while read file; do
	if [ -z "$(tail -n 1 ${file} | tr '\n' '~' | grep '~$')" ]; then
		echo >> ${file}
		echo "===> Added final newline to ${file##./}"
	fi
done

comment="$(make -V COMMENT)"
if [ -n "$(echo ${comment} | grep -E '^(A|An) ')" ]; then
	new_comment="$(echo ${comment} | awk '{ 
		gsub("^(A|An) ", "", $0); 
		print toupper( substr($0, 1, 1) ) substr($0, 2);
	}')"
	sed_expr="s|^COMMENT=.*|COMMENT=	${new_comment}|"
	echo "===> Removed leading article from COMMENT"
fi
reinplace_file Makefile "${sed_expr}"

if [ -f "${descr_file}" ]; then	
	sed_expr=""
	if [ -n "$(grep '^Author:' ${descr_file})" ]; then
		sed_expr="/^Author:/d;"
		echo "===> Deleting Author: line from description file"
	fi

	if [ -n "$(grep -E '^WWW:(	| {2,})' ${descr_file})" ]; then
		sed_expr="${sed_expr} s#^WWW:(	| {2,})#WWW: #g;"
		echo "===> Fixing WWW: line in description file"
	fi
	reinplace_file "${descr_file}" "${sed_expr}"
else
	echo "===> Port's description file is missing"
fi

if [ -n "$(whereis -bq portlint)" ]; then
	echo "===> Portlint output:"
	portlint -abt
else
	echo "===> Portlint not found, skipping port checks"
fi
