#!/bin/sh

readonly aspell_check="aspell --dont-backup --lang=en check"

skip_spellcheck=0

display_usage() {
	echo "Usage: pcheck [-h|-s]"
	echo ""
	echo "    -h - show this help"
	echo "    -s - skip spellcheck"
	echo ""
	exit
}

reinplace_file() {
	local file="$1" expr="$2"
	
	[ -n "$expr" ] || return
	sed "$expr" $file > $file.new
	mv $file.new $file
}

while getopts "hs" option; do
	case $option in
	s)
		skip_spellcheck=1 ;;
	*)
		display_usage
	esac
done

if [ -z "$(make -V PKGNAME 2>/dev/null)" ]; then
	echo "===> This is not port directory"
	exit 1
fi

rej_files="$(find . -name "*.rej")"
if [ -n "$rej_files" ]; then
	echo "===> Found rejected patch file(s)"
	echo " $rej_files" | sed 's|./||g'
	exit 1
fi

find . \( -name "*.orig" -or -size 0 \) -delete

if [ $skip_spellcheck -eq 0 ]; then
	if [ -n "$(whereis -bq aspell)" ]; then
		$aspell_check pkg-descr
		[ -f pkg-message ] && $aspell_check pkg-message
		[ -f files/pkg-message.in ] && $aspell_check files/pkg-message.in
	else
		echo "===> Aspell not found, skipping spellcheck"
	fi
fi

find . \( -type f -and ! -path './work/*' \) | while read file; do
	if [ -z "$(tail -n 1 $file | tr '\n' '~' | grep '~$')" ]; then
		echo >> $file
		echo "===> Added final newline to ${file##./}"
	fi
done

comment="$(make -V COMMENT)"
if [ -n "$(echo $comment | grep -E '^(A|An) ')" ]; then
	new_comment="$(echo $comment | awk '{ 
		gsub("^(A|An) ", "", $0); 
		print toupper( substr($0, 1, 1) ) substr($0, 2);
	}')"
	sed_expr="s|^COMMENT=.*|COMMENT=	$new_comment|"
	echo "===> Removed leading article from COMMENT"
fi
reinplace_file Makefile "$sed_expr"

sed_expr=""
if [ -n "$(grep '^Author:' pkg-descr)" ]; then
	sed_expr="/^Author:/d;"
	echo "===> Deleting Author: line from pkg-descr"
fi

if [ -n "$(grep '^WWW:	' pkg-descr)" ]; then
	sed_expr="$sed_expr s|^WWW:	|WWW: |g;"
	echo "===> Fixing tab after WWW: in pkg-descr"
fi
reinplace_file pkg-descr "$sed_expr"

if [ -n "$(whereis -bq portlint)" ]; then
	echo "===> Portlint output:"
	portlint -abt
else
	echo "===> Portlint not found, skipping port checks"
fi
