#!/bin/sh

readonly PORTSDIR=${PORTSDIR:-/usr/ports}
if [ -d "${PORTSDIR}" ]; then
	echo "===> Ports directory not found: ${PORTSDIR}" >&2
	echo "===> Try setting PORTSDIR enviroment variable" >&2
	exit 1
fi

readonly base_dir="${PWD}"
readonly category="$(make -V CATEGORIES | awk '{print $1}')"
readonly port="$(basename ${PWD})"

portdir_clean() {
	local dir="${1}"
	
	if [ -d "${dir}/work" ]; then
		cd "${dir}"
		if [ "$(make clean 2>/dev/null | grep 'not writable')" ]; then
			echo "===> Failed to make clean in ${dir}" >&2
			exit 1
		fi
	fi
	find "${dir}" -name "*.(orig|rej)" -or -size 0 -delete > /dev/null
}

if [ ! "${port}" -o ! "${category}" ]; then
	echo "===> This is not port directory" >&2
	exit 1
fi

new_ver_dir="${category}/${port}"
old_ver_dir="${PORTSDIR}/${new_ver_dir}"

portdir_clean "${PWD}"

if [ -d "${old_ver_dir}" ]; then
	portdir_clean "${old_ver_dir}"
else
	echo "===> Orginal port directory does not exist" >&2
	exit 1
fi

cd "${base_dir}/../../" && diff -urN ${*} "${old_ver_dir}" "${new_ver_dir}"
