#!/bin/sh

readonly PORTSDIR=${PORTSDIR:-/usr/ports}
readonly base_dir=$PWD
readonly category=$(make -V CATEGORIES | awk '{print $1}')
readonly port=$(basename $PWD)

portdir_clean() {
	local dir=$1
	
	if [ -d "$dir/work" ]; then
		cd "$dir"
		if [ -n "$(make clean | grep 'not writable')" ]; then
			echo "===> Failed to make clean in $dir"
			exit
		fi
	fi
	find "$dir" -name "*.(orig|rej)" -or -size 0 -delete > /dev/null
}

if [ -z "$port" -o -z "$category" ]; then
	echo "===> This is not port directory"
	exit
fi

new_ver_dir="$category/$port"
old_ver_dir="$PORTSDIR/$new_ver_dir"

portdir_clean "$PWD"

if [ -d "$old_ver_dir" ]; then
	portdir_clean "$old_ver_dir"
else
	echo "===> Orginal port directory does not exist"
	exit
fi

cd "$base_dir/../../" && diff -urN $* "$old_ver_dir" "$new_ver_dir"
