#!/bin/sh

PORTSDIR=${PORTSDIR:-/usr/ports}
[ -d "${PORTSDIR}" ] || \
	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
if [ ! -d "${PORTSDIR}" ]; then
	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable"
	exit 1
fi

display_usage() {
	<< EOF cat
Usage: pfind [-c category] [-h] [-m maintainer] [-n name] [-s string]

    -c - port category
    -h - show this help
    -m - port's maintainer
    -n - port's name
    -s - string to find in port's Makefile

EOF
	exit
}

while getopts "c:hm:n:s:" option; do
	case ${option} in
	c)
		if [ ! -d ${PORTSDIR}/${OPTARG} ]; then
			echo "No such category: ${OPTARG}"
			exit 1
		fi
		category="${OPTARG}/" ;;
	m)
		maintainer="${OPTARG}" ;;
	n)
		name="${OPTARG}" ;;
	s)
		string="${OPTARG}" ;;
	*)
		display_usage
	esac
done

[ -z "${category}" -a -z "${maintainer}" -a -z "${name}" -a -z "${string}" ] && \
	display_usage

[ -z "${category}" ] || search_args="path=${PORTSDIR}/${category}"
[ -z "${maintainer}" ] || search_args="${search_args} maint=${maintainer}"
[ -z "${name}" ] || search_args="${search_args} name=${name}"

cd ${PORTSDIR}
if [ ! -f "$(make -VINDEXFILE)" ]; then
	echo "===> Fetching missing index file"
	make fetchindex || exit 1
fi

make quicksearch ${search_args} | awk '/^Path:/ { print $2 }' | while read portdir; do
	if [ -n "${string}" ]; then
		[ -e ${portdir}/Makefile ] || continue
		[ -n "$(grep "${string}" ${portdir}/Makefile)" ] || continue
	fi  
	echo ${portdir} | sed "s|${PORTSDIR}/||"
done
