#!/bin/sh

PORTSDIR=${PORTSDIR:-/usr/ports}

display_usage() {
	<< EOF >&2 cat
Usage: ${0##*/} [ -b bdep ] [-c category] [-h] [-m maintainer] [-n name] [-s string]

    -b - port needing certain build dependency
    -c - port category
    -h - show this help
    -m - port maintainer
    -n - port name
    -s - string to find in port Makefile

EOF
	exit 1
}

while getopts "b:c:hm:n:s:" option; do
	case ${option} in
	b)
		bdeps="${OPTARG}" ;;
	c)
		category="${OPTARG}" ;;
	m)
		maintainer="${OPTARG}" ;;
	n)
		name="${OPTARG}" ;;
	s)
		string="${OPTARG}" ;;
	*)
		display_usage
	esac
done

[ -z "${bdeps}" -a -z "${category}" -a -z "${maintainer}" -a -z "${name}" \
	-a -z "${string}" ] && display_usage

[ -d "${PORTSDIR}" ] || \
	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
if [ ! -d "${PORTSDIR}" ]; then
	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
	exit 1
fi

if [ -n "${category}" -a ! -d ${PORTSDIR}/${category} ]; then
	echo "No such category: ${category}" >&2
	exit 1
fi

[ -z "${bdeps}" ] || search_args="bdeps=${bdeps}"
[ -z "${category}" ] || search_args="${search_args} path=${PORTSDIR}/${category}/"
[ -z "${maintainer}" ] || search_args="${search_args} maint=${maintainer}"
[ -z "${name}" ] || search_args="${search_args} name=${name}"

cd ${PORTSDIR}
if [ ! -f "$(make -VINDEXFILE)" ]; then
	echo "===> Fetching missing index file"
	make fetchindex || exit 1
fi

if [ -z "${search_args}" ]; then
	find . -name Makefile -depth 3 -exec grep -l "${string}" {} \; \
		2>/dev/null | sed 's|^.\/||; s|\/Makefile$||' | sort
	exit
fi

make quicksearch ${search_args} | awk '/^Path:/ { print $2 }' | while read portdir; do
	if [ -n "${string}" ]; then
		[ -e ${portdir}/Makefile ] || continue
		[ -n "$(grep "${string}" ${portdir}/Makefile)" ] || continue
	fi  
	echo ${portdir} | sed "s|${PORTSDIR}/||"
done
