#!/bin/sh

readonly FREEBSD_LOGIN="${FREEBSD_LOGIN:-$USER}"
readonly PKGNAME="$(make -V PKGNAME 2>/dev/null)"
readonly TBDIR="${TBDIR:-/usr/local/tinderbox}"
readonly UID="$(id -u)"

tc_cmd() {
	local tc_script
	
	if [ $UID -eq 0 ]; then
		tc_script="./tc"
	else
		tc_script="sudo ./tc"
	fi

	cd $TBDIR/scripts && $tc_script $*
}

if [ -z "$PKGNAME" ]; then
	echo "===> This is not port directory"
	exit 1
fi

builds="$1"
if [ -z "$builds" ]; then
	for build in $(tc_cmd listBuilds); do
		if [ -f "$TBDIR/logs/$build/$PKGNAME.log" ]; then
			logfile="$TBDIR/logs/$build/$PKGNAME.log"
			break
		fi
	done
	
	if [ -z "$logfile" ]; then
		echo "===> Could not find any build logs for $PKGNAME"
		exit 1
	fi
else
	logfile="$TBDIR/logs/$builds/$PKGNAME.log"
	if [ ! -f "$logfile" ]; then
		echo "===> Logfile $logfile does not exist"
		exit 1
	fi
fi

echo "===> Build selected: $build"
echo "===> Uploading to http://people.freebsd.org/~$FREEBSD_LOGIN/buildlogs/$PKGNAME.log"
scp "$logfile" $FREEBSD_LOGIN@freefall.freebsd.org:public_html/buildlogs/
exit $?
