#!/bin/sh

readonly PATHFIX=$(make -V USES | grep pathfix >/dev/null; echo ${?})
readonly PATHFILE="$(make -V PATHFIX_MAKEFILEIN)"
readonly PKGNAME="$(make -V PKGNAME 2>/dev/null)"
readonly cmd="${1:-check}"

if [ -z "${PKGNAME}" ]; then
	echo "===> This is not port directory" >&2
	exit 1
fi

if [ ! -d work ]; then
	echo "===> No work directory" >&2
	exit 1
fi

if [ "${cmd}" = "show" ]; then
	shift
	patterns="${@}"
fi

find work -name "*.bak" -print | while read file; do
	case ${cmd} in
	check)
		#TODO Makefile.in may be changed by REINPLACE_CMD too, fix it
		[ ${PATHFIX} -eq 0 -a \
			"$(basename ${file%.bak})" = "${PATHFILE}" ] && continue
		[ -z "$(diff "${file}" "${file%.bak}")" ] && \
			echo "File ${file%.bak} not modified" ;;
	show)
		if [ -n "${patterns}" ]; then
			matched=0
			for p in ${patterns}; do
				case ${file%.bak} in *${p}*)
					matched=1
					break
				esac
			done
			[ ${matched} -eq 1 ] || continue
		fi
		diff -u "${file}" "${file%.bak}"
	esac
done 
